# Generated by Django 3.1.3 on 2020-11-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindles',
            name='time_posted',
        ),
    ]
