# Generated by Django 3.1.3 on 2020-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0002_remove_vindles_time_posted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vindles',
        ),
    ]
