# Generated by Django 3.1.3 on 2020-11-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0004_vindles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vindles',
        ),
    ]
