# Generated by Django 3.1.3 on 2020-11-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0006_vindles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindles',
            name='user_id',
        ),
    ]
