# Generated by Django 3.1.3 on 2020-11-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0008_vindles_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindles',
            name='user_id',
        ),
    ]
