# Generated by Django 3.1.3 on 2020-11-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0011_auto_20201126_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vindles',
        ),
    ]
