# Generated by Django 3.1.3 on 2020-12-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0015_auto_20201127_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vindles',
        ),
    ]
