# Generated by Django 3.1.3 on 2021-01-06 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vindler', '0018_vindlesprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlesprofilepicture',
            name='image',
            field=models.ImageField(default='defaultp.jpg', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='vindlesprofilepicture',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
