# Generated by Django 3.1.3 on 2021-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0019_auto_20210106_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vindlesprofilepicture',
            old_name='owner',
            new_name='idd',
        ),
        migrations.AlterField(
            model_name='vindlesprofilepicture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
