# Generated by Django 3.1.3 on 2021-01-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0020_auto_20210107_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindlesprofilepicture',
            name='idd',
        ),
        migrations.DeleteModel(
            name='Vindles',
        ),
        migrations.DeleteModel(
            name='VindlesProfilePicture',
        ),
    ]
