# Generated by Django 3.1.3 on 2021-01-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0022_vindles_vindlesprofilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindlesprofilepicture',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vindles',
        ),
        migrations.DeleteModel(
            name='VindlesProfilePicture',
        ),
    ]
