# Generated by Django 3.1.3 on 2021-01-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0024_vindles_vindlesprofilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlesprofilepicture',
            name='image',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
