# Generated by Django 3.1.3 on 2021-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0025_auto_20210108_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlesprofilepicture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
