# Generated by Django 3.1.3 on 2021-01-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vindler', '0026_auto_20210108_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vindlesprofilepicture',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vindles',
        ),
        migrations.DeleteModel(
            name='VindlesProfilePicture',
        ),
    ]
