export const GET_VINDLES="GET_VINDLES";
export const DELETE_VINDLE="DELETE_VINDLE";
export const ADD_VINDLE="ADD_VINDLE";
export const GET_USER_VINDLES="GET_USER_VINDLES";


export const GET_ERRORS="GET_ERRORS";
export const CREATE_MESSAGE="CREATE_MESSAGE";

export const USER_LOADING="USER_LOADING";
export const USER_LOADED="USER_LOADED";
export const AUTH_ERROR="AUTH_ERROR";

export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";

export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const CPD_TOGGLE_SUCCESS="CPD_TOGGLE_SUCCESS";

export const SCROLL_SUCCESS="SCROLL_SUCCESS";
export const NO_SCROLL="NO_SCROLL";

export const SEARCH_USER="SEARCH_USER";
export const CLOSE_SEARCH_DIV="CLOSE_SEARCH_DIV";

export const MESSAGE_SEARCH_USER="MESSAGE_SEARCH_USER";

export const ADD_VINDLE_MESSAGE_LIST="ADD_VINDLE_MESSAGE_LIST";
export const GET_VINDLE_MESSAGE_LIST="GET_VINDLE_MESSAGE_LIST";


export const DISPLAY_CHAT_SUCCESS ="DISPLAY_CHAT_SUCCESS";


export const  PROFILE_PICTURE_SUCCESS = "PROFILE_PICTURE_SUCCESS";
export const GET_PROFILE_PICTURE = "GET_PROFILE_PICTURE";

export const HOME_PROFILE_PICTURE = "HOME_PROFILE_PICTURE";

export const DISPLAY_UPLOAD_DIV = "DISPLAY_UPLOAD_DIV";

export const  CLOSE_UPLOAD_DIV = "CLOSE_UPLOAD_DIV";