# Generated by Django 3.1.3 on 2020-12-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vindlemessages', '0003_auto_20201228_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlemessages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
