# Generated by Django 3.1.3 on 2020-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vindlemessages', '0004_auto_20201228_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlemessages',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
