# Generated by Django 3.1.1 on 2020-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faceauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.TextField(max_length=60)),
                ('train_images', models.ImageField(upload_to='train_images')),
            ],
        ),
    ]
