# Generated by Django 3.1.1 on 2022-01-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VindlerFaceauthMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VindlerPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='for_predictions')),
            ],
        ),
        migrations.CreateModel(
            name='VindlerFaceauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_images', models.ImageField(blank=True, upload_to='train_images')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grantaccess.vindlerfaceauthmapper')),
            ],
        ),
    ]
