# Generated by Django 3.1.1 on 2020-09-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceauth',
            name='train_images',
            field=models.ImageField(blank=True, upload_to='train_images'),
        ),
    ]
