# Generated by Django 3.1.1 on 2022-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlerfaceauthmapper',
            name='targets',
            field=models.TextField(max_length=30),
        ),
    ]
