# Generated by Django 3.1.1 on 2020-10-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0002_auto_20200903_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faceauth',
        ),
    ]
