# Generated by Django 3.1.1 on 2022-01-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0002_auto_20220123_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vindlerfaceauthmapper',
            name='targets',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
