# Generated by Django 3.1.1 on 2020-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grantaccess', '0005_auto_20201022_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faceauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.TextField(max_length=60)),
                ('train_images', models.ImageField(blank=True, upload_to='train_images')),
            ],
        ),
    ]
