# Generated by Django 3.1.1 on 2020-10-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0006_faceauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faceauth',
        ),
    ]
