# Generated by Django 3.1.1 on 2020-10-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0008_faceauth_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faceauth',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
