# Generated by Django 3.1.1 on 2020-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantaccess', '0010_faceauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faceauth',
        ),
    ]
